# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '培训机构'), (2, '高校'), (3, '个人')], default=1, verbose_name='机构类别'),
        ),
    ]
